{
 "title": "Python-Transmission",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "torrent_name",
    "query": {
     "query": "label_values(transmission_torrent_download_rate,torrent)"
    }
   },
   { "name": "job", "query": "${VAR_JOB}" }
  ]
 },
 "panels": [
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "transmission_server_version" }
   ]
  },
  {
   "title": "Number of torrents",
   "type": "stat",
   "description": "Total number of torrents in transmission",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_torrent_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "transmission_download_speed{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "transmission_upload_speed{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RPC version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "transmission_rpc_version" }
   ]
  },
  { "title": "Per Torrent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Download Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "transmission_torrent_download_rate{job=\"$job\", torrent=\"$torrent_name\"}"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "transmission_torrent_upload_rate{job=\"$job\", torrent=\"$torrent_name\"}"
    }
   ]
  },
  {
   "title": "Peers uploading to us",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "transmission_torrent_peers_sending_to_us{name=\"$torrent_name\"}"
    }
   ]
  },
  {
   "title": "Peers downloading from us",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "transmission_torrent_peers_getting_from_us{name=\"$torrent_name\"}"
    }
   ]
  }
 ]
}